"""Alembic environment for RED's PostgreSQL schema.

ADR 0003: RED's schema changes ship as migrations committed with the code. This
environment reads the connection string from ``DATABASE_URL`` (SPEC.md section
10: secrets stay outside Git, supplied by the platform) and runs the ordered
migration scripts in this directory. RED's migrations are written as raw SQL,
so no ORM metadata is autogenerated; ``target_metadata`` stays ``None`` on
purpose because the domain models are plain dataclasses, not SQLAlchemy models.

The URL scheme is normalised to SQLAlchemy's psycopg 3 dialect so a plain
``postgresql://`` URL, as documented for the local compose database, works
without the caller knowing the driver dialect.
"""

from __future__ import annotations

import os

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config


def _database_url() -> str | None:
    url = os.environ.get("DATABASE_URL")
    if url and url.startswith("postgresql://"):
        return "postgresql+psycopg://" + url[len("postgresql://") :]
    return url


_url = _database_url()
if _url:
    config.set_main_option("sqlalchemy.url", _url)

target_metadata = None


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live database connection."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Apply migrations against the live ``DATABASE_URL`` database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
