"""Generated canon ops workflow metadata (K14; ADR 0014). DO NOT EDIT.

Regenerate with:
  uv run python -m redops.workflows.sop_import --canon <RALPH_CANON> \
      --red-out backend/redops/workflows/ops_documents_gen.py \
      --cockpit-out vendor/openexecutive/packages/core/openexecutive/workflows/redops_sops.py
"""

# Metadata derived from the pinned canon's docs/ops/sops and docs/ops/playbooks.
# ``sop_library`` builds the durable workflow definitions from this data; the
# cockpit catalog builds its Jobs entries from the same shapes.

OPS_DOCUMENT_META: tuple[dict, ...] = (
    {
        'definition_id': 'red-sop-ad-campaign-setup',
        'kind': 'sop',
        'title': 'Ad campaign setup SOP',
        'summary': 'This procedure sets up and launches one simple ad campaign. The funnel is live. The ads specialist starts this procedure in the Traffic station. - Ads specialist: builds and runs the campaign. - Delivery lead: owns the budget. - Coach: checks the numbers. - Client: approves the budget. 1. Set up tra',
        'version': '1.b125b8d2',
        'decisions': ['If leads are cheap but do not book, check the funnel.', 'If the learning phase is not done, do not judge the ad.', 'If two hooks run at once, kill the weaker one.', 'If you want to model a proven funnel, map it first and do not copy it.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Set up tracking, audiences, and goals.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Work out the value of a lead with the funnel math.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Build one campaign.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Build one ad set with a few ads.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Bid for the result you want, like a purchase or a booking.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the ad copy with the one message.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Test two hooks against the same body.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Launch the campaign.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Leave it alone for about 10 days.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Wait for about 25 to 45 conversions.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Check the few key numbers.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Change one thing at a time.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the budget.'}],
        'slug': 'ad-campaign-setup',
        'source': 'docs/ops/sops/ad-campaign-setup.md',
        'roles': [['Ads specialist', 'builds and runs the campaign.'], ['Delivery lead', 'owns the budget.'], ['Coach', 'checks the numbers.'], ['Client', 'approves the budget.']],
    },
    {
        'definition_id': 'red-sop-authority-video-build',
        'kind': 'sop',
        'title': 'Authority video build SOP',
        'summary': 'This procedure builds the authority video from the six blocks. The offer is approved. The producer starts this procedure in the Funnel station. - Producer: records and edits. - Delivery lead: writes the script. - Coach: checks the script against the offer. - Client: records the video. 1. Gather the ',
        'version': '1.0ce65168',
        'decisions': ['If the script is long, cut the context block first.', 'If the proof is thin, use a customer result or a borrowed result.', 'If the slides are made before the script, stop and fix the script.', 'If the video is over 20 minutes, trim it.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Gather the one currency, the message, and the roadmap.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write the promise block.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the proof block. Lead with the best result.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write the problems block. Name three obstacles.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write the steps block. Show three phases and nine steps.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the context block. Say who you are and why you.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Write the action block. One clear next step.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Check the script is right before the slides.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Build the slides from the script.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Record the video.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Edit the video and add captions.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Cut the same script into nine short step videos.'}, {'name': 'step-13', 'kind': 'task', 'title': 'Post the videos on the page.'}],
        'slug': 'authority-video-build',
        'source': 'docs/ops/sops/authority-video-build.md',
        'roles': [['Producer', 'records and edits.'], ['Delivery lead', 'writes the script.'], ['Coach', 'checks the script against the offer.'], ['Client', 'records the video.']],
    },
    {
        'definition_id': 'red-sop-brain-dump-to-roadmap',
        'kind': 'sop',
        'title': 'Brain dump to roadmap SOP',
        'summary': 'This procedure turns a raw brain dump into a product roadmap. The one currency and message are approved. The delivery lead starts this procedure in the Offer station. - Delivery lead: runs the dump and shapes the roadmap. - Coach: checks the weakest-link test. - Client: dumps the ideas and approves ',
        'version': '1.6c4a10c6',
        'decisions': ['If a step is not essential, cut it.', 'If there are more than three stages, merge them.', 'If a step has no deliverable, design one.', 'If the client wants to skip the dump, say no. The dump finds the product.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Dump every step, topic, and question the buyer faces between point A and'}, {'name': 'step-02', 'kind': 'task', 'title': 'Pull more ideas from books, courses, reviews, and search.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Group the ideas into themes.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Remove anything that is not essential.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Run the weakest-link test. If a step is removed, does the outcome break?'}, {'name': 'step-06', 'kind': 'task', 'title': 'Force the rest into three stages.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Break each stage into three steps.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Break each step into three actions.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Give every step one clear action.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Give every step one deliverable.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Name the roadmap for the person and the result.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Get feedback before design.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: dumps the ideas and approves the roadmap.'}],
        'slug': 'brain-dump-to-roadmap',
        'source': 'docs/ops/sops/brain-dump-to-roadmap.md',
        'roles': [['Delivery lead', 'runs the dump and shapes the roadmap.'], ['Coach', 'checks the weakest-link test.'], ['Client', 'dumps the ideas and approves the roadmap.']],
    },
    {
        'definition_id': 'red-sop-call-audit',
        'kind': 'sop',
        'title': 'Call audit SOP',
        'summary': 'This procedure reviews a recorded enrollment call and finds the weak gate. A call is recorded. The coach starts this procedure every week. - Coach: reviews the call. - Enrollment specialist: runs the call. - Delivery lead: owns the fix. 1. Listen to the recorded call. 2. Note where the call ended: w',
        'version': '1.816e559b',
        'decisions': ['If most calls end at one gate, fix the script for that gate.', 'If the specialist talks too much, practice listening.', 'If a price is quoted early, fix the sequence.', 'If a call ends at a no, treat it as a success.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Listen to the recorded call.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Note where the call ended: which gate.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Check the intent gate.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Check the commitment gate.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Check the clarity gate.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Check the confidence gate.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Check the desire gate.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Note one thing that worked.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Note one thing to fix.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Fix the script or the practice.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Track the end points across calls.'}],
        'slug': 'call-audit',
        'source': 'docs/ops/sops/call-audit.md',
        'roles': [['Coach', 'reviews the call.'], ['Enrollment specialist', 'runs the call.'], ['Delivery lead', 'owns the fix.']],
    },
    {
        'definition_id': 'red-sop-case-study-capture',
        'kind': 'sop',
        'title': 'Case study capture SOP',
        'summary': 'This procedure turns a client result into a story. It covers confirm the result, get permission, write, approve, and publish. A client hits a goal or gets a clear win. The delivery lead starts this procedure within one week. - Delivery lead: confirms the result and asks for permission. - Writer: wri',
        'version': '1.d50ae4ca',
        'decisions': ['If the result is not clear, wait. Do not write a story on a guess.', 'If the client says no, stop. Do not publish anything.', 'If the client wants to stay private, hide the name and the details.', 'If the numbers are weak, use the story of the change, not the size.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Confirm the result. Check the numbers against the goals set at kickoff.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Gather the facts. Note the start point, the change, and the end point.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Get permission. Ask the client in writing if we can share the story.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Set the terms. Agree on what we can name and what we must hide.'}, {'name': 'step-05', 'kind': 'task', 'title': "Write the story. Use the client's words. Keep it short and clear."}, {'name': 'step-06', 'kind': 'task', 'title': 'Add the proof. Put in the numbers and one short quote.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Send it for approval. Give the client time to read and change it.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Fix the story. Make the changes the client asks for.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Publish the story. Put it where the plan says. Tell the client.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Save the file. Put the final story and the permission note in the folder.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: reviews the story and approves it.'}],
        'slug': 'case-study-capture',
        'source': 'docs/ops/sops/case-study-capture.md',
        'roles': [['Delivery lead', 'confirms the result and asks for permission.'], ['Writer', 'writes the story.'], ['Client', 'reviews the story and approves it.']],
    },
    {
        'definition_id': 'red-sop-certification-exam',
        'kind': 'sop',
        'title': 'Certification exam SOP',
        'summary': 'This procedure trains and certifies an operator. A team is ready to run the system. The delivery lead starts this procedure in the Serve stage. - Delivery lead: owns the standard and the exam. - Coach: trains the operator. - Operator: learns and takes the exam. - Client: names the team. 1. Write the',
        'version': '1.630bca5c',
        'decisions': ['If the operator has no real result, wait before certifying.', 'If the exam is too easy, raise the pass mark.', 'If a skill is missing, add training before the exam.', 'If a standard is old, update it at the yearly recheck.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Write the short list of skills an operator must hold.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Train the operator on the [playbooks](../index.md) and the [roadmap](../checklists/product-roadmap.md).'}, {'name': 'step-03', 'kind': 'task', 'title': 'Have the operator run real work with a coach watching.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Set the exam and a clear pass mark.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Test the operator against the standard.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Certify the ones who pass.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Keep a register of certified people.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Recheck the standard every year.'}],
        'slug': 'certification-exam',
        'source': 'docs/ops/sops/certification-exam.md',
        'roles': [['Delivery lead', 'owns the standard and the exam.'], ['Coach', 'trains the operator.'], ['Operator', 'learns and takes the exam.'], ['Client', 'names the team.']],
    },
    {
        'definition_id': 'red-sop-client-onboarding',
        'kind': 'sop',
        'title': 'Client onboarding SOP',
        'summary': 'This procedure starts a new client well. It covers the welcome, the goals, the start date, access, the plan, and the first module. A client signs the agreement and pays the first invoice. The delivery lead starts this procedure within two business days. - Delivery lead: owns the whole procedure and ',
        'version': '1.a04dadd6',
        'decisions': ['If the client has no clear goal, pause and help them set one. Do not start', 'If the client cannot start on the planned date, move the date. Tell the coach.', 'If the client needs extra access, ask the delivery lead to approve it.', 'If the client is not ready, keep them in pre-sell. Do not force the start.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Send the welcome note. Thank the client. Name the delivery lead and the'}, {'name': 'step-02', 'kind': 'task', 'title': 'Book the kickoff call. Put it on the calendar within five business days.'}, {'name': 'step-03', 'kind': 'task', 'title': "Collect the client's goals. Ask for the numbers they want to hit. Ask for"}, {'name': 'step-04', 'kind': 'task', 'title': 'Set the success goals. Write one goal for the program. Make it specific and'}, {'name': 'step-05', 'kind': 'task', 'title': 'Set the start date. Pick the first day of the program. Tell the client.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Set up access. Give the client their login. Give them the call links and the'}, {'name': 'step-07', 'kind': 'task', 'title': 'Build the one-page plan. Put the goals, the dates, and the modules on one'}, {'name': 'step-08', 'kind': 'task', 'title': 'Assign the first module. Tell the client what to do before the first call.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Run the kickoff. Walk through the plan. Answer questions. Confirm the start'}, {'name': 'step-10', 'kind': 'task', 'title': 'Save the notes. Put the plan and the goals in the client folder.'}],
        'slug': 'client-onboarding',
        'source': 'docs/ops/sops/client-onboarding.md',
        'roles': [['Delivery lead', 'owns the whole procedure and the client relationship.'], ['Coach', 'joins the kickoff and leads the first module.'], ['Enrollment specialist', 'hands over the client notes and the sales context.']],
    },
    {
        'definition_id': 'red-sop-community-launch',
        'kind': 'sop',
        'title': 'Community launch SOP',
        'summary': 'This procedure opens and runs a controlled group. The lead magnet and the funnel work. The community manager starts this procedure in the Content station. - Community manager: runs the group and the welcome. - Delivery lead: owns the plan and the calendar. - Coach: checks the offer fit. - Client: po',
        'version': '1.e1ac55f0',
        'decisions': ['If the group is dead, add lives and two-step posts.', 'If a hand-raise waits, answer it the same day.', 'If a post leaves the offer, cut it.', 'If the group is small, keep it simple and focus on warmth.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Name the group for the person and the result.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write a clear description with one action.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the welcome post.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Add the filter question: "Do you want to learn more?"'}, {'name': 'step-05', 'kind': 'task', 'title': 'Tag members who raise their hand.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Plan a simple post calendar.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Post two-step posts, lives, and case studies.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Keep every post inside the offer.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Reply to hand-raisers the same day.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Invite warm members to a call.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Nurture the rest for about 90 days.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Reuse each asset in the other channels.'}],
        'slug': 'community-launch',
        'source': 'docs/ops/sops/community-launch.md',
        'roles': [['Community manager', 'runs the group and the welcome.'], ['Delivery lead', 'owns the plan and the calendar.'], ['Coach', 'checks the offer fit.'], ['Client', 'posts as the expert.']],
    },
    {
        'definition_id': 'red-sop-community-moderation',
        'kind': 'sop',
        'title': 'Community Moderation SOP',
        'summary': 'This procedure keeps the client community safe and kind. A new member joins. Or a post breaks a rule. Or a member reports a problem. The community manager runs this procedure. The coach answers method questions. The partnership lead handles member issues. 1. Welcome each new member. Share the [rules',
        'version': '1.c38dd853',
        'decisions': ['If a post is spam, remove it and warn the member.', 'If a post is rude, hide it and talk to the member.', 'If a member repeats a break, pause their access.', 'If a post is a threat, remove it and tell the owner at once.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Welcome each new member. Share the [rules](../checklists/community-rules.md) and the start guide.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Watch the feed each day. Read new posts and replies.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Act on rule breaks. Warn first, then remove.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Record each action. Note the member, the post, and the reason.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Report the week. Share what you saw and what you did.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Thank good members. Point out helpful posts.'}],
        'slug': 'community-moderation',
        'source': 'docs/ops/sops/community-moderation.md',
        'roles': [],
    },
    {
        'definition_id': 'red-sop-content-crusher-build',
        'kind': 'sop',
        'title': 'Content crusher build SOP',
        'summary': 'This procedure fills one content crusher for one step of the offer. The product roadmap is approved. The producer starts this procedure in the Content station. - Producer: fills the crusher. - Delivery lead: picks the step. - Coach: checks the offer fit. - Client: approves the sheet. 1. Pick one ste',
        'version': '1.8a660626',
        'decisions': ['If there is no deliverable, design one before slides.', 'If the promise has no metric or timeline, fix it.', 'If the sheet leaves the offer, cut the part that does not fit.', 'If it is too long, move detail to the call.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pick one step of the roadmap.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write the topic and title.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the promise with a metric and a timeline.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Name the top three frustrations.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write the goal the buyer wants.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Pick one image or metaphor.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Name the deliverable for the step.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Write the three how-to actions.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Add one example or proof.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Write one decision point.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Write one action for the buyer.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Check the sheet lives inside the offer.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the sheet.'}],
        'slug': 'content-crusher-build',
        'source': 'docs/ops/sops/content-crusher-build.md',
        'roles': [['Producer', 'fills the crusher.'], ['Delivery lead', 'picks the step.'], ['Coach', 'checks the offer fit.'], ['Client', 'approves the sheet.']],
    },
    {
        'definition_id': 'red-sop-course-production',
        'kind': 'sop',
        'title': 'Course production SOP',
        'summary': 'This procedure records, edits, and publishes the modules fast. The slide decks are approved. The producer starts this procedure in the Delivery station. - Producer: records and edits. - Client: records the lessons. - Delivery lead: owns the plan and the dates. - Coach: checks each module. 1. Build a',
        'version': '1.5561d4e9',
        'decisions': ['If a lesson runs long, split it into two.', 'If the sound is bad, re-record the take.', 'If a module has no deliverable, add one before publishing.', 'If a live cohort is running, record live and reuse it.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Build a production plan with the days and the modules.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Set up the camera, mic, and light.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write short speaker notes for each slide.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Record one slide per take.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Clap or snap at the start of each take.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Record in wide screen at high quality.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Keep each lesson between 5 and 30 minutes.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Cut at the clap or snap marks.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Smooth the sound and remove noise.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Add captions.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Publish each module to the course site.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Add the deliverable for each step.'}],
        'slug': 'course-production',
        'source': 'docs/ops/sops/course-production.md',
        'roles': [['Producer', 'records and edits.'], ['Client', 'records the lessons.'], ['Delivery lead', 'owns the plan and the dates.'], ['Coach', 'checks each module.']],
    },
    {
        'definition_id': 'red-sop-email-sequence-build',
        'kind': 'sop',
        'title': 'Email sequence build SOP',
        'summary': 'This procedure builds one nurture sequence for one funnel step. The roadmap and the content plan are ready. The producer starts this procedure in the Content station. - Producer: writes the emails. - Delivery lead: owns the plan. - Coach: checks the offer fit. - Client: approves the emails. 1. Pick ',
        'version': '1.59c72ecb',
        'decisions': ['If an email has no action, add one.', 'If promotion is over the cap, add more value emails.', 'If a lead acts, stop the sequence for that step.', 'If opens are low, rewrite the subject line.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pick the funnel step and the goal.'}, {'name': 'step-02', 'kind': 'task', 'title': "List the buyer's common questions for that step."}, {'name': 'step-03', 'kind': 'task', 'title': 'Write a value email.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write a problem email.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write an offer email.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Use the 5P types: Problem, Promise, Proof, Ping, Promotion.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Add one clear action to every email.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Keep promotion to about one in five.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Build the full 27-part sequence.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Reuse the slides as emails.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Schedule the sends.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Send until the lead acts.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the emails.'}],
        'slug': 'email-sequence-build',
        'source': 'docs/ops/sops/email-sequence-build.md',
        'roles': [['Producer', 'writes the emails.'], ['Delivery lead', 'owns the plan.'], ['Coach', 'checks the offer fit.'], ['Client', 'approves the emails.']],
    },
    {
        'definition_id': 'red-sop-enrollment-asset-build',
        'kind': 'sop',
        'title': 'Enrollment asset build SOP',
        'summary': 'This procedure builds the sales asset. It covers gather inputs, write the script, set checkpoints, write objections, practice, and review. A client buys the enrollment service. The enrollment specialist starts this procedure in the Launch stage. - Enrollment specialist: owns the asset and writes the',
        'version': '1.78d5995f',
        'decisions': ['If the one currency is missing, stop. Get it before you write.', 'If a checkpoint fails on most calls, fix the script, not the lead.', 'If the client wants pressure, say no. Keep the call honest.', 'If the team cannot run the script, practice again before launch.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Gather the inputs. Get the one currency, the roadmap, and the price.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Study the buyer. List the top pains, goals, and fears.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the script. Follow the call shape: frame, diagnose, invite.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write the questions. Ask for exact current numbers and goal numbers.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Set the checkpoints. Use intent, commitment, value, confidence, and desire.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the objections. List the common doubts and a question for each one.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Build the card. Put the checkpoints on one page.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Practice the script. Run role play with the client and their team.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Review the calls. Listen to recorded calls and note where each call ended.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Fix the asset. Update the script and the card from what you learn.'}],
        'slug': 'enrollment-asset-build',
        'source': 'docs/ops/sops/enrollment-asset-build.md',
        'roles': [['Enrollment specialist', 'owns the asset and writes the script.'], ['Delivery lead', "gives the client's one currency and roadmap."], ['Client and team', 'practice the script and give feedback.']],
    },
    {
        'definition_id': 'red-sop-funnel-build',
        'kind': 'sop',
        'title': 'Funnel build SOP',
        'summary': 'This procedure builds the short funnel from opt in to booked call. The offer and the message are approved. The delivery lead starts this procedure in the Funnel station. - Delivery lead: runs the build. - Producer: builds the pages and the video. - Coach: checks the script and the pages. - Client: r',
        'version': '1.0fd148c4',
        'decisions': ['If the script is weak, stop before slides.', 'If opt-in is low, test the title and the image.', 'If show rate is low, tighten the 72-hour window and confirmations.', 'If the funnel leaks, check each page in order.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Gather the signature solution, the message, and the brand assets.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write the authority video script with the six blocks.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Check the script before the slides.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Build the opt-in page.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Add the two-step opt in.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Build the video page.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Build the booking page with the calendar.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Add the 72-hour booking window.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Build the confirmation page.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Add a pre-call homework page.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Add three or four confirmations.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Test each page on a phone.'}, {'name': 'step-13', 'kind': 'task', 'title': 'Turn the funnel on.'}],
        'slug': 'funnel-build',
        'source': 'docs/ops/sops/funnel-build.md',
        'roles': [['Delivery lead', 'runs the build.'], ['Producer', 'builds the pages and the video.'], ['Coach', 'checks the script and the pages.'], ['Client', 'records the video.']],
    },
    {
        'definition_id': 'red-sop-lead-magnet-build',
        'kind': 'sop',
        'title': 'Lead magnet build SOP',
        'summary': 'This procedure builds one lead magnet from one step of the offer. The funnel is being built. The producer starts this procedure in the Funnel station. - Producer: builds the cheat sheet and the PDF. - Delivery lead: picks the step. - Coach: checks the offer fit. - Client: approves the asset. 1. Pick',
        'version': '1.0c6ad356',
        'decisions': ['If the magnet is long, cut it to one page.', 'If it gives the full answer, remove the last step.', 'If it is a quiz or an ebook, rebuild it as a cheat sheet.', 'If opt-in is low, test a new title first.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pick one hot step of the signature solution.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Name the magnet for the person and the result.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the one-page cheat sheet.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Keep it to about ten minutes of use.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Leave one step for the call.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Build the short PDF: title, proof, bio, problem, steps, and action.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Use a picture of the thing itself.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Add a second click before the page.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Set the PDF to send by email.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Pair the magnet with the authority video.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Test two titles and keep the winner.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the asset.'}],
        'slug': 'lead-magnet-build',
        'source': 'docs/ops/sops/lead-magnet-build.md',
        'roles': [['Producer', 'builds the cheat sheet and the PDF.'], ['Delivery lead', 'picks the step.'], ['Coach', 'checks the offer fit.'], ['Client', 'approves the asset.']],
    },
    {
        'definition_id': 'red-sop-million-dollar-message',
        'kind': 'sop',
        'title': 'Million dollar message SOP',
        'summary': 'This procedure writes the one message from the one currency. The currency calculator is done. The delivery lead starts this procedure in the Message station. - Delivery lead: writes the message. - Coach: runs the filters. - Client: approves the message. 1. Take the approved one currency. 2. Add the ',
        'version': '1.33bef7cc',
        'decisions': ['If it has no metric, add a number.', 'If it has no timeline, use the length of the program.', 'If the buyers do not react, ask them which problem to solve first.', 'If it does not fit one line, it is not ready.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Take the approved one currency.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Add the metric.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Add the timeline.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Name the three main frictions.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write the message: "I help [person] get [result] in [time] without'}, {'name': 'step-06', 'kind': 'task', 'title': 'Run the 3 a.m. test. Does it wake the buyer up?'}, {'name': 'step-07', 'kind': 'task', 'title': 'Check it is a painkiller, not a vitamin.'}, {'name': 'step-08', 'kind': 'task', 'title': "Check it is in the buyer's own words."}, {'name': 'step-09', 'kind': 'task', 'title': 'Read it out loud. Cut any hype.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Repeat three or four times until it lands.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Get the message approved.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Save it as the master. Use pieces of it everywhere.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the message.'}],
        'slug': 'million-dollar-message',
        'source': 'docs/ops/sops/million-dollar-message.md',
        'roles': [['Delivery lead', 'writes the message.'], ['Coach', 'runs the filters.'], ['Client', 'approves the message.']],
    },
    {
        'definition_id': 'red-sop-module-delivery',
        'kind': 'sop',
        'title': 'Module delivery SOP',
        'summary': 'This procedure delivers one module of the program. It covers prepare, teach, coach, check, and record. The client starts a new module week. The coach runs this procedure once for each module. - Coach: prepares the module, teaches it, and coaches the client. - Delivery lead: checks the module fits th',
        'version': '1.30f29f1d',
        'decisions': ['If the client did not do the pre-work, coach on the gap first. Do not teach', 'If the client fails the gate, repeat the module. Do not move on.', 'If the module does not fit the plan, tell the delivery lead before you teach.', 'If the client is stuck, slow down. Use a smaller step.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Prepare the module. Read the module goal. Check it fits the one-page plan.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Prepare the materials. Get the slides, the worksheet, and the example ready.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Send the pre-work. Tell the client what to do before the teach call.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Teach the module. Explain the idea in plain words. Show one example.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Coach the client. Help them apply the idea to their own work.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Check the work. Look at what the client made. Give clear feedback.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Check the gate. Confirm the client passed the module gate before moving on.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Record the result. Note what the client did and what comes next.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Send the recap. Give the client the next step and the next call date.'}],
        'slug': 'module-delivery',
        'source': 'docs/ops/sops/module-delivery.md',
        'roles': [['Coach', 'prepares the module, teaches it, and coaches the client.'], ['Delivery lead', 'checks the module fits the plan and the goals.'], ['Client', 'does the work and brings questions to the call.']],
    },
    {
        'definition_id': 'red-sop-outreach-sequence',
        'kind': 'sop',
        'title': 'Outreach sequence SOP',
        'summary': 'This procedure books calls with warm contacts. The group and the funnel work. The setter starts this procedure on the run line. - Setter: sends the messages and books calls. - Delivery lead: owns the sequence and the target. - Coach: checks tone and fit. - Client: approves the messages. 1. Start wit',
        'version': '1.e264de75',
        'decisions': ['If the contact is cold, do not message. Wait for warmth.', 'If there is no reply after the polite close, stop.', 'If a fit is poor, end the triage kindly.', 'If someone asks to stop, remove them at once.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Start with warm contacts only.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Reply to a post or comment first.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Engage for a day or two.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Send the first short, helpful message.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Send a soft bump if there is no reply.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Send one polite close.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Stop after the polite close.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Book a short triage call on interest.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Check fit on the triage call.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Book the main call for fits.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Keep a simple pipeline: new, warm, booked, closed.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the messages.'}],
        'slug': 'outreach-sequence',
        'source': 'docs/ops/sops/outreach-sequence.md',
        'roles': [['Setter', 'sends the messages and books calls.'], ['Delivery lead', 'owns the sequence and the target.'], ['Coach', 'checks tone and fit.'], ['Client', 'approves the messages.']],
    },
    {
        'definition_id': 'red-sop-pricing-review',
        'kind': 'sop',
        'title': 'Pricing review SOP',
        'summary': 'This procedure reviews and updates the price of an offer. The offer has run for about 90 days. The delivery lead starts this procedure. - Delivery lead: owns the price. - Coach: checks the value. - Client: approves the change. 1. Pull the funnel numbers. 2. Work out the value of one client. 3. Check',
        'version': '1.75287493',
        'decisions': ['If close rate is high, the price may be too low.', 'If sales are strong, raise the price. Expect a small drop.', 'If a lead asks for a discount, shorten the path instead.', 'If value has not changed, keep the price.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pull the funnel numbers.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Work out the value of one client.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Check the cost per client against the value.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Review the close rate on calls.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Look for ways to raise value: more deliverables or a bundle.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Raise the price if value is proven.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Add or update a payment plan.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Keep the no-discount rule.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Update the guarantee or the no-guarantee rule.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Update the funnel math.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the change.'}],
        'slug': 'pricing-review',
        'source': 'docs/ops/sops/pricing-review.md',
        'roles': [['Delivery lead', 'owns the price.'], ['Coach', 'checks the value.'], ['Client', 'approves the change.']],
    },
    {
        'definition_id': 'red-sop-quarterly-review',
        'kind': 'sop',
        'title': 'Quarterly Review SOP',
        'summary': 'This procedure reviews the plan every 90 days. The quarter ends. Or 90 days pass since the last review. The delivery lead runs this procedure. The coach gives progress notes. The partnership lead gives renewal and referral numbers. 1. Gather the numbers. Pull revenue, clients, cost per lead, and cos',
        'version': '1.5d3bdd8d',
        'decisions': ['If a goal is met, raise it or keep it.', 'If a goal is missed, find the cause first.', 'If a channel works, put more into it.', 'If a channel fails, pause it and test one change.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Gather the numbers. Pull revenue, clients, cost per lead, and cost per client.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Compare the numbers to the goals in the plan.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Note what worked and what did not.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Decide what to keep, stop, or change.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Update the one-page plan. Set new goals for the next 90 days.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Share the plan with the team.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Set the date for the next review.'}],
        'slug': 'quarterly-review',
        'source': 'docs/ops/sops/quarterly-review.md',
        'roles': [],
    },
    {
        'definition_id': 'red-sop-referral',
        'kind': 'sop',
        'title': 'Referral SOP',
        'summary': 'This procedure turns a happy client into a new client. A client hits a result. Or a client says something good about the work. The partnership lead runs this procedure. The delivery lead flags the moment. The coach shares praise from sessions. 1. Watch for the moment. A result, a win, or a kind word',
        'version': '1.721dce25',
        'decisions': ['If the client is happy, ask right away.', 'If the client is busy, ask at the next check-in.', 'If the client is not happy, fix the work first.', 'If a referral does not fit, say so and keep the relationship.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Watch for the moment. A result, a win, or a kind word.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Ask the client for a referral. Be direct and calm.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Make it easy. Give a short note the client can forward.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Name the kind of person you want to meet.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Track each ask and each name in one list.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Follow up on each name within two days.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Thank the client. Send a note or a small gift.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Tell the client what happened with the referral.'}],
        'slug': 'referral',
        'source': 'docs/ops/sops/referral.md',
        'roles': [],
    },
    {
        'definition_id': 'red-sop-renewal',
        'kind': 'sop',
        'title': 'Renewal SOP',
        'summary': "This procedure keeps a client for another term. The client's term is 60 days from its end. Or the client's results are strong and the next step is clear. The partnership lead runs this procedure. The delivery lead gives the results. The coach gives progress notes. 1. Pull the [client scorecard](../c",
        'version': '1.ab7dcf6d',
        'decisions': ['If results are strong, offer the next step.', 'If results are weak, fix the work first. Do not offer yet.', 'If the client is quiet, run a win-back talk.', 'If the client says no, ask why. Save the reason.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pull the [client scorecard](../checklists/client-scorecard.md). Check attendance, progress, and results.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Run a health check. Ask the client how the work feels.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Review the results against the goals from kickoff.'}, {'name': 'step-04', 'kind': 'task', 'title': "Pick the next step. Match it to the client's new goal."}, {'name': 'step-05', 'kind': 'task', 'title': 'Build a simple offer for the next term.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Share the offer on a call. Do not rush.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Answer questions. Ask for a clear yes or no.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Close the renewal. Set the new start date.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Send a short thank-you note.'}],
        'slug': 'renewal',
        'source': 'docs/ops/sops/renewal.md',
        'roles': [],
    },
    {
        'definition_id': 'red-sop-reputation',
        'kind': 'sop',
        'title': 'Reputation SOP',
        'summary': 'This procedure grows reviews, stories, and press for RED. A client hits a result. Or a review window opens. Or a press chance appears. The partnership lead runs this procedure. The delivery lead flags results. The community manager shares member stories. 1. Ask happy clients for a review. Send a dir',
        'version': '1.c7cab8f0',
        'decisions': ['If a review is bad, reply in private first. Fix the issue.', 'If a story needs approval, get it before you publish.', 'If press asks for a quote, keep it short and true.', 'If a claim is not proven, do not publish it.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Ask happy clients for a review. Send a direct link.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Collect the review. Save it in one place.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Ask for a short story. Use the [case study checklist](../checklists/case-study.md).'}, {'name': 'step-04', 'kind': 'task', 'title': 'Publish the review and the story. Use the site and social channels.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Track each review and each mention. Note the date and the source.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Reach out to press when a story is strong.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Thank each person who gives a review or a story.'}],
        'slug': 'reputation',
        'source': 'docs/ops/sops/reputation.md',
        'roles': [],
    },
    {
        'definition_id': 'red-sop-retargeting-setup',
        'kind': 'sop',
        'title': 'Retargeting setup SOP',
        'summary': 'This procedure sets up retargeting for every funnel step. The ad campaign is live. The ads specialist starts this procedure in the Retargeting station. - Ads specialist: builds the audiences and the ads. - Delivery lead: owns the plan and the budget. - Coach: checks the tracking. - Client: approves ',
        'version': '1.c2844189',
        'decisions': ['If the same ad goes to everyone, split the audiences.', 'If buyers see the ad, add the buyer list to the exclude group.', 'If the cost is high, shrink the audience and rewrite the ad.', 'If tracking is missing, stop and fix it first.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Add tracking and goals to every funnel step.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Split audiences by where each person stopped.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Name the group to include.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Name the group to exclude, like buyers.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write one focused ad for each group.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Use the 5P types for the ad copy.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Show the ad to small groups at low cost.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Measure the result and repeat.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the plan.'}],
        'slug': 'retargeting-setup',
        'source': 'docs/ops/sops/retargeting-setup.md',
        'roles': [['Ads specialist', 'builds the audiences and the ads.'], ['Delivery lead', 'owns the plan and the budget.'], ['Coach', 'checks the tracking.'], ['Client', 'approves the plan.']],
    },
    {
        'definition_id': 'red-sop-role-play-practice',
        'kind': 'sop',
        'title': 'Role-play practice SOP',
        'summary': 'This procedure drills the team on the enrollment call. It covers set the scene, run the call, score, coach, and repeat. The enrollment asset is ready, or the team needs practice. The enrollment specialist runs this procedure before live calls. - Enrollment specialist: runs the drill and scores the c',
        'version': '1.9ad83414',
        'decisions': ['If the seller fails a gate, stop and coach. Do not run the whole call again.', 'If the lead is too easy, make the doubt harder.', 'If the seller feels stuck, slow down and drill one gate.', 'If the team keeps missing one doubt, update the [objection sheet](../checklists/objection-sheet.md).'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Set the scene. Pick one lead type and one doubt to work on.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Set the goal. Name the one skill the seller must show.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Run the call. Let the seller run the script from start to end.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Play the lead. Raise real doubts. Do not make it easy.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Score the call. Use the [checkpoint card](../checklists/checkpoint-card.md). Mark each gate pass or fail.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Coach on one thing. Give one clear fix. Show the better words.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Run it again. Repeat the same scene with the fix.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Swap roles. Let the seller play the lead to feel the other side.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Note the pattern. Write down the doubt that keeps coming up.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Repeat. Drill until the seller passes the gates with no pressure.'}],
        'slug': 'role-play-practice',
        'source': 'docs/ops/sops/role-play-practice.md',
        'roles': [['Enrollment specialist', 'runs the drill and scores the calls.'], ['Seller', 'plays the caller and runs the script.'], ['Partner', 'plays the lead and gives the doubts.']],
    },
    {
        'definition_id': 'red-sop-session-coaching',
        'kind': 'sop',
        'title': 'Session coaching SOP',
        'summary': 'This procedure coaches a client on a call. It covers open, review, coach, commit, and close. A coaching call is on the calendar. The coach runs this procedure at the start of the call. - Coach: runs the call and leads the coaching. - Client: brings their work and their questions. - Delivery lead: ge',
        'version': '1.32a52bb5',
        'decisions': ['If the client has no work to review, coach on why. Do not move to a new topic.', 'If the client is stuck on a block, pick a smaller step.', 'If the client needs a plan change, tell the delivery lead after the call.', 'If the client is upset, listen first. Then coach.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Open the call. Set the time, the purpose, and the outcome.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Review the last step. Ask what the client did since the last call.'}, {'name': 'step-03', 'kind': 'task', 'title': "Review the numbers. Look at the client's progress against the goals."}, {'name': 'step-04', 'kind': 'task', 'title': 'Coach on one thing. Pick the one block that matters most. Work on it.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Ask questions. Let the client find the answer. Do not solve it for them.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Agree on the next step. Make it small and clear.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Get a commitment. Ask the client to say what they will do and by when.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Close the call. Recap the step. Confirm the next call date.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Send the note. Give the client the recap and the next step.'}],
        'slug': 'session-coaching',
        'source': 'docs/ops/sops/session-coaching.md',
        'roles': [['Coach', 'runs the call and leads the coaching.'], ['Client', 'brings their work and their questions.'], ['Delivery lead', 'gets a note if the client needs a plan change.']],
    },
    {
        'definition_id': 'red-sop-slide-deck-build',
        'kind': 'sop',
        'title': 'Slide deck build SOP',
        'summary': 'This procedure turns a content crusher into a module slide deck. The content crushers are filled. The producer starts this procedure in the Delivery station. - Producer: builds the deck. - Delivery lead: owns the template. - Coach: checks the slides against the script. - Client: approves the deck. 1',
        'version': '1.80bcec5d',
        'decisions': ['If a slide has two ideas, split it.', 'If an image is off brand, replace it.', 'If the deck does not match the script, fix the deck.', 'If a borrowed image has no credit, add it.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Open the [slide template](../checklists/slide-template.md).'}, {'name': 'step-02', 'kind': 'task', 'title': 'Add the title and the promise slide.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Add one emotional image per slide.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Keep text short. No long bullet lists.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Add the three how-to action slides.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Add the example or proof slide.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Add the deliverable slide.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Add the action slide.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Apply the brand colors and fonts.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Give credit for any borrowed image.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Check the slides match the script.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Export the deck.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the deck.'}],
        'slug': 'slide-deck-build',
        'source': 'docs/ops/sops/slide-deck-build.md',
        'roles': [['Producer', 'builds the deck.'], ['Delivery lead', 'owns the template.'], ['Coach', 'checks the slides against the script.'], ['Client', 'approves the deck.']],
    },
    {
        'definition_id': 'red-sop-strategy-session-run',
        'kind': 'sop',
        'title': 'Strategy session run SOP',
        'summary': 'This procedure runs one paid roadmap session. A lead pays for a session. The enrollment specialist starts this procedure in the Launch stage. - Enrollment specialist: runs the session. - Delivery lead: owns the offer and the price. - Coach: reviews recorded sessions. - Client: approves the roadmap. ',
        'version': '1.4ec02e14',
        'decisions': ['If the lead is not a fit, end the session kindly.', 'If confidence is low at the first question, go back to the plan.', 'If it is a no, keep the plan and the goodwill.', 'If the fee is not credited, fix the offer.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Confirm the session and the fee.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Gate the session with a short application.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Review the lead against the roadmap before the call.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Open the call: time, purpose, and outcome.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Audit each roadmap step. Ask for exact numbers.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Build the 90-day plan with the lead.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Ask the three questions.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Invite the lead to the program.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Apply the fee to month one.'}, {'name': 'step-10', 'kind': 'task', 'title': 'If it is a no, end well and give the plan.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the roadmap.'}],
        'slug': 'strategy-session-run',
        'source': 'docs/ops/sops/strategy-session-run.md',
        'roles': [['Enrollment specialist', 'runs the session.'], ['Delivery lead', 'owns the offer and the price.'], ['Coach', 'reviews recorded sessions.'], ['Client', 'approves the roadmap.']],
    },
    {
        'definition_id': 'red-sop-webinar-build',
        'kind': 'sop',
        'title': 'Webinar build SOP',
        'summary': 'This procedure builds and runs a webinar. The simple path works. The delivery lead starts this procedure in the Funnel station. - Delivery lead: owns the run of show. - Producer: builds the slides and the pages. - Coach: checks the teach and the offer. - Client: presents the webinar. 1. Plan the tit',
        'version': '1.5c57a195',
        'decisions': ['If the webinar is cold, advertise a lead magnet first.', 'If the teach is too deep, cut the how and keep the what.', 'If the replay page has player controls, remove them.', 'If conversion is under 10% live, fix the offer before automating.'],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Plan the title, the offer, and the price.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Build the slides from the content crushers.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the frame block.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write three teach blocks, one per phase.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Teach the what, not the how.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the shift block.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Write the sell block.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Write the show block.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Build the pages: sign up, train, webinar, replay, order.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Send the invite and reminder emails.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Run the webinar live.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Send the replay to everyone.'}, {'name': 'step-13', 'kind': 'task', 'title': 'Run the closing sequence for 3 to 5 days.'}, {'name': 'step-14', 'kind': 'task', 'title': 'Automate after ten live runs at 10% or better.'}],
        'slug': 'webinar-build',
        'source': 'docs/ops/sops/webinar-build.md',
        'roles': [['Delivery lead', 'owns the run of show.'], ['Producer', 'builds the slides and the pages.'], ['Coach', 'checks the teach and the offer.'], ['Client', 'presents the webinar.']],
    },
    {
        'definition_id': 'red-playbook-authority-video',
        'kind': 'playbook',
        'title': 'Authority video playbook',
        'summary': 'This playbook builds the authority video: the short video that shows the offer. Build one short video that shows the signature solution and builds trust. Good looks like a video that runs 8 to 20 minutes and follows one clear script. The same script also runs ads, emails, and sales letters. Use this',
        'version': '1.2c26164b',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Write the promise block. Name the person, the result, and the time.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write the proof block. Give your best results first.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the problems block. Name the three main obstacles.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write the steps block. Show the path in three phases and nine steps.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write the context block. Say who you are and why you.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the action block. One clear next step.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Check the script is right before you make slides.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Build slides from the script.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Record the video.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Edit the video and add captions.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Cut the same script into nine short step videos.'}],
        'slug': 'authority-video',
        'source': 'docs/ops/playbooks/authority-video.md',
        'roles': [['Delivery lead', 'owns the script.'], ['Producer', 'records and edits.'], ['Coach', 'checks the script against the offer.'], ['Client', 'records the video.']],
    },
    {
        'definition_id': 'red-playbook-certification',
        'kind': 'playbook',
        'title': 'Certification playbook',
        'summary': "This playbook certifies a team so they can run the RED Method without us. Train and certify the client's team. Good looks like a team that can build the machine, run the calls, and hold the standard. Certification proves they can. Use this playbook in the Serve and Partner stages. Offer it when the ",
        'version': '1.454e64cf',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Name the skills an operator must hold.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Train the team on the [playbooks](../index.md) and the [roadmap](../checklists/product-roadmap.md).'}, {'name': 'step-03', 'kind': 'task', 'title': 'Have each person run real work with a coach watching.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Set the exam. A clear pass mark.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Test each person against the standard.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Certify the people who pass.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Keep a register of certified people.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Recheck the standard every year.'}],
        'slug': 'certification',
        'source': 'docs/ops/playbooks/certification.md',
        'roles': [['Delivery lead', 'owns the standard and the exam.'], ['Coach', 'trains the team.'], ['Certified operator', 'runs the system day to day.'], ['Client', 'names the team.']],
    },
    {
        'definition_id': 'red-playbook-content',
        'kind': 'playbook',
        'title': 'Content playbook',
        'summary': 'This playbook builds an audience with content that lives inside the signature solution. Build a content engine that grows the audience. Every piece of content must live inside the signature solution. The content teaches the one currency. It moves people toward the offer. Use this playbook at Station',
        'version': '1.c8a9a8b9',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pull the nine steps of the signature solution into one list.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Fill one content crusher per step.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Turn each step into a content theme.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write five messages per step, one per 5P type.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Build a content roadmap for the next 90 days.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Plan each piece: format, channel, and date.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Produce one asset at a time.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Publish the asset on three channels.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Promote the asset with a small paid push.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Reuse the asset in new formats.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Build retargeting audiences from video views.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Review the numbers each week and repeat what works.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the plan and shares the content.'}],
        'slug': 'content',
        'source': 'docs/ops/playbooks/content.md',
        'roles': [['Delivery lead', 'owns the roadmap and the results.'], ['Content producer', 'makes the posts, emails, and videos.'], ['Coach', 'checks that each piece fits the offer.'], ['Client', 'approves the plan and shares the content.']],
    },
    {
        'definition_id': 'red-playbook-delivery',
        'kind': 'playbook',
        'title': 'Delivery playbook',
        'summary': 'This playbook delivers the RED program to the client and creates real results. The client serves their own customers. We build the machine. They run it. Onboard the client well. Deliver one module per week for 6 to 12 weeks. Teach on one day and coach on another. Track progress. Collect a case study',
        'version': '1.0d979a8a',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Onboard the client with a welcome and a kickoff.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Set success goals and a start date.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Build the module plan for 6 to 12 weeks.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Produce one module per week. Use the [content crusher](../checklists/content-crusher.md) and the [slide template](../checklists/slide-template.md).'}, {'name': 'step-05', 'kind': 'task', 'title': 'Teach the module on one day.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Coach the client on another day.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Track attendance, progress, and results.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Review the [scorecard](../checklists/client-scorecard.md) each week.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Audit the client against the roadmap every 90 days.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Fix what is stuck.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Collect a case study the moment results land.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Turn each finished step into a small offer.'}],
        'slug': 'delivery',
        'source': 'docs/ops/playbooks/delivery.md',
        'roles': [['Delivery lead', 'owns the client relationship and the results.'], ['Coach', 'teaches and coaches the client.'], ['Producer', 'builds each module.'], ['Client', 'does the work and shares the numbers.']],
    },
    {
        'definition_id': 'red-playbook-email-nurture',
        'kind': 'playbook',
        'title': 'Email and nurture playbook',
        'summary': 'This playbook keeps the audience warm over time with email and a nurture sequence. Build one nurture sequence that runs on its own. Good looks like a set of emails that go out in order and move a lead one step at a time. Most leads buy later, not now, so follow-up matters. Use this playbook on the r',
        'version': '1.60431063',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pull the nine steps of the signature solution.'}, {'name': 'step-02', 'kind': 'task', 'title': 'For each step, plan a value email, a pain email, and an offer email.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the emails. Use the 5P types.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Build one sequence of 27 parts: three types times nine steps.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Add one clear action to every email.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Keep the promotion cap. About one in five.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Build one sequence for each funnel step.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Send the sequence until the lead acts.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Reuse your slides as emails.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Review open and click rates each week.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the emails.'}],
        'slug': 'email-nurture',
        'source': 'docs/ops/playbooks/email-nurture.md',
        'roles': [['Delivery lead', 'owns the list and the sequence.'], ['Producer', 'writes the emails.'], ['Coach', 'checks the offer fit.'], ['Client', 'approves the emails.']],
    },
    {
        'definition_id': 'red-playbook-enroll',
        'kind': 'playbook',
        'title': 'Enroll playbook',
        'summary': 'This playbook turns a booked call into a paying client. Run a calm enrollment call. Frame the call. Diagnose the gap. Invite with no pressure. Every gate passes before the invite. The call ends in a clear yes or a clear no. Use this playbook at Station 8, after the funnel and traffic are live. Use i',
        'version': '1.bd486842',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Prep before the call. Read the lead notes and the roadmap.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Frame the call: set the time, purpose, and outcome.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Check intent. End early if the lead is not a fit.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Audit the lead against the roadmap. Ask for exact numbers.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Do not solve or pitch yet.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Check commitment. Get a 5 before you prescribe.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Check clarity and confidence.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Check who decides and the timing.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Give a short plan.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Ask: if the plan and price work, are they ready to start?'}, {'name': 'step-11', 'kind': 'task', 'title': 'Invite with no pressure.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Answer doubts with questions, not pressure.'}, {'name': 'step-13', 'kind': 'task', 'title': 'Track why each call ends.'}, {'name': 'step-14', 'kind': 'task', 'title': 'Offer a paid strategy call for premium offers.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the script.'}],
        'slug': 'enroll',
        'source': 'docs/ops/playbooks/enroll.md',
        'roles': [['Enrollment specialist', 'runs the call.'], ['Delivery lead', 'owns the script and the checkpoints.'], ['Coach', 'reviews recorded calls.'], ['Client', 'approves the script.']],
    },
    {
        'definition_id': 'red-playbook-enrollment-service',
        'kind': 'playbook',
        'title': 'Enrollment service playbook',
        'summary': "This playbook builds a done-for-you enrollment asset for the client. Help the client enroll more customers without feeling pushy or fake. Write the script from the client's one currency and roadmap. Build the question set. Set the checkpoints. Write objection answers. Practice with role play. Review",
        'version': '1.14cfd9ff',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Write the script from the one currency and roadmap.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Build the question set: current numbers, goal numbers, and gaps.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Set the checkpoints: intent, commitment, clarity, confidence, and desire.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write answers to the common objections.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Build the application and the booking page.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Set the 72-hour booking window.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Add a pre-call homework page.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Practice with the client and their team using role play.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Review recorded calls and note where each call ended.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Fix the script and repeat.'}],
        'slug': 'enrollment-service',
        'source': 'docs/ops/playbooks/enrollment-service.md',
        'roles': [['Enrollment specialist', 'builds and runs the asset.'], ['Delivery lead', 'owns the client relationship.'], ['Coach', 'runs the role play.'], ['Client and team', 'learn and run the script.']],
    },
    {
        'definition_id': 'red-playbook-funnel',
        'kind': 'playbook',
        'title': 'Funnel playbook',
        'summary': 'This playbook builds the simple path that turns a stranger into a booked call. Build a simple path that turns a stranger into a booked call. Good looks like a live funnel and a finished authority video. Keep the path short. Friction is the enemy. Use this after the offer. It is Station 4. - Delivery',
        'version': '1.c2ff0041',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Write a short video that shows the signature solution.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Use the six blocks: promise, proof, problems, steps, context, action.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Check the script is right before you make slides.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Build four pages: opt in, video, calendar, and confirmation.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Add a second click before the video. This is the two-step opt in.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Add branding to the slides and pages. Keep one look.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Record the video. Keep it 8 to 20 minutes.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Edit the video and add captions.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Add a homework page before the call so people show up ready.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Confirm the call more than once. Add a reminder the day before.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Turn the funnel on.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Test one thing at a time, starting at the top of the funnel.'}],
        'slug': 'funnel',
        'source': 'docs/ops/playbooks/funnel.md',
        'roles': [['Delivery lead', 'runs the build.'], ['Coach', 'checks the script and the pages.'], ['Client', 'records the video.']],
    },
    {
        'definition_id': 'red-playbook-lead-magnet',
        'kind': 'playbook',
        'title': 'Lead magnet playbook',
        'summary': 'This playbook turns one step of the offer into a small, useful lead magnet. Build one lead magnet that attracts the right person. Good looks like a one-page cheat sheet and a short PDF that pair with the authority video. Do not build a lead magnet from scratch. Use this playbook in the Funnel statio',
        'version': '1.eefc41a8',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Pick one hot step of the signature solution.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Name the magnet for the person and the result.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the one-page cheat sheet.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Wrap it in a short PDF: title, proof, a short bio, the problem, the steps,'}, {'name': 'step-05', 'kind': 'task', 'title': 'Pair the magnet with the authority video.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Use one image, the picture of the thing itself.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Add a second click before the page. This is the two-step opt in.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Send the magnet by email, not on the thank-you page.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Test it and keep the winner.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the asset.'}],
        'slug': 'lead-magnet',
        'source': 'docs/ops/playbooks/lead-magnet.md',
        'roles': [['Delivery lead', 'picks the step and owns the asset.'], ['Producer', 'builds the cheat sheet and the PDF.'], ['Coach', 'checks the asset grabs the right person.'], ['Client', 'approves the asset.']],
    },
    {
        'definition_id': 'red-playbook-market',
        'kind': 'playbook',
        'title': 'Market playbook',
        'summary': 'This playbook finds the one market and the one avatar you can reach and serve. Find one market you can reach and serve. Good looks like a clear avatar snapshot and a goals grid. The market work follows the one currency. We research the problem, not just the person. Use this after the plan. It is Sta',
        'version': '1.88958e7f',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Size the market on social networks.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Size the market on business networks.'}, {'name': 'step-03', 'kind': 'task', 'title': 'List the top pains of the buyer.'}, {'name': 'step-04', 'kind': 'task', 'title': 'List the top goals of the buyer.'}, {'name': 'step-05', 'kind': 'task', 'title': 'List the top fears of the buyer.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Check the market has profit, presence, and a path to reach people.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Narrow many markets down to one.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Pick one avatar for the first step of the offer.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Fill in the avatar goals grid.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Ask the market one question: "If I could solve one problem for you in the'}],
        'slug': 'market',
        'source': 'docs/ops/playbooks/market.md',
        'roles': [['Delivery lead', 'runs the research.'], ['Coach', 'checks the market fit.'], ['Client', 'shares what they know about the buyer.']],
    },
    {
        'definition_id': 'red-playbook-message',
        'kind': 'playbook',
        'title': 'Message playbook',
        'summary': 'This playbook turns a category into one currency and one clear message. Pick one currency and write one message. Good looks like one measured result with a metric and a timeline. The message names the person, the result, and the time, and the friction we remove. Use this after the market. It is Stat',
        'version': '1.54e9740a',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'List every result you could sell. Use the two columns.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Pick the one result that is critical and specific.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Ask the market which problem they want solved first.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Give the result a metric.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Give the result a timeline. The length of the program can be the timeline.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Name the three main obstacles the buyer faces.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Write one message. Tie the person, the result, and the time together.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Run the message through the filters.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Get the message approved. Expect three or four passes.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the message.'}],
        'slug': 'message',
        'source': 'docs/ops/playbooks/message.md',
        'roles': [['Delivery lead', 'runs the session.'], ['Coach', 'pushes for one clear result.'], ['Client', 'approves the message.']],
    },
    {
        'definition_id': 'red-playbook-numbers',
        'kind': 'playbook',
        'title': 'Numbers playbook',
        'summary': 'This playbook shows how the numbers fit together across the whole method. Understand the few numbers that decide the business. Good looks like one page of numbers that the team watches every week. The master number is the lifetime value of a client. Use this playbook in the Plan station and again on',
        'version': '1.f13adb8e',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Write the price of the offer.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Work out the value of one lead. Price divided by 100 is the planning figure.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Work out the cost per lead.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Work out the cost per booked call.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Work out the cost per client.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Work out the lifetime value of a client.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Compare the cost per client to the lifetime value.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Change one number. Watch the chain move.'}],
        'slug': 'numbers',
        'source': 'docs/ops/playbooks/numbers.md',
        'roles': [['Delivery lead', 'owns the numbers.'], ['Coach', 'checks the numbers against the plan.'], ['Client', 'gives the real numbers.']],
    },
    {
        'definition_id': 'red-playbook-offer',
        'kind': 'playbook',
        'title': 'Offer playbook',
        'summary': 'This playbook packages the work into a product with a price. Package the work into a product with a price. Good looks like a profit pyramid, a signature solution, a product roadmap, and a price. The offer solves one important problem in a crowded market. Use this after the message. It is Station 3. ',
        'version': '1.cdd873ed',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Split the market into four levels by success.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Choose which levels you serve and which you do not.'}, {'name': 'step-03', 'kind': 'task', 'title': "Build a visual path from the buyer's pain to the goal."}, {'name': 'step-04', 'kind': 'task', 'title': 'Give the path three phases and nine steps.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Give every step one clear action and one deliverable.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Run the digital brain dump to fill the steps. See the [roadmap SOP](../sops/brain-dump-to-roadmap.md).'}, {'name': 'step-07', 'kind': 'task', 'title': 'Shape the steps with the rule of threes.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Choose how you deliver: group program, one to one, or done for you.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Set a premium price. Start at $3,000 or more.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Outline a 6 to 12 week program, one module per week.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Plan how the price can be paid. Add a payment plan.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Get feedback before design.'}],
        'slug': 'offer',
        'source': 'docs/ops/playbooks/offer.md',
        'roles': [['Delivery lead', 'runs the design.'], ['Coach', 'checks the path and the price.'], ['Client', 'gives feedback before design.']],
    },
    {
        'definition_id': 'red-playbook-outreach',
        'kind': 'playbook',
        'title': 'Outreach playbook',
        'summary': 'This playbook turns warm contacts into appointments with a simple message sequence. Book calls with people who already know you. Good looks like a short, friendly sequence that leads to a call. Use it with people who joined the group or opted in. Do not message strangers. Use this playbook on the ru',
        'version': '1.136b49c1',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Start with people who joined the group or opted in.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Reply to a comment or post first.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Connect and engage for a day or two.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Send the first short, helpful message.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Send a soft bump if there is no reply.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Send one polite close. Then stop.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Book a short triage call when they show interest.'}, {'name': 'step-08', 'kind': 'task', 'title': 'On the triage call, check fit and book the main call.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Keep a simple pipeline: new, warm, booked, and closed.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Keep a healthy pace. Do not flood one person with messages.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the messages.'}],
        'slug': 'outreach',
        'source': 'docs/ops/playbooks/outreach.md',
        'roles': [['Setter', 'sends the messages and books calls.'], ['Delivery lead', 'owns the sequence and the target.'], ['Coach', 'checks the tone and the fit.'], ['Client', 'approves the messages.']],
    },
    {
        'definition_id': 'red-playbook-partnership',
        'kind': 'playbook',
        'title': 'Partnership playbook',
        'summary': 'This playbook keeps clients for years as their results and assets grow. Keep every client for the long term. Hold regular check-ins. Watch for quiet or stuck clients. Offer the next step. Build a community. Ask for referrals. Renew and expand. Use this playbook in the Grow and Partner stages, after ',
        'version': '1.b7d0d93e',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Hold regular check-ins.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Watch for clients who are quiet or stuck.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Reach out to quiet clients with a simple offer of help.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Offer the next step at the right time.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Slice the offer into a small entry and a mid offer.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Build a community of clients.'}, {'name': 'step-07', 'kind': 'task', 'title': "Certify the client's team so they can run the system."}, {'name': 'step-08', 'kind': 'task', 'title': 'Ask happy clients for referrals.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Renew and expand the work.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Track reviews, stories, and press.'}],
        'slug': 'partnership',
        'source': 'docs/ops/playbooks/partnership.md',
        'roles': [['Partnership lead', 'owns the relationship and the renewal.'], ['Community manager', 'runs the client community.'], ['Delivery lead', 'shares client results.'], ['Client', 'stays engaged and grows.']],
    },
    {
        'definition_id': 'red-playbook-plan',
        'kind': 'playbook',
        'title': 'Plan playbook',
        'summary': 'This playbook sets the numbers and the plan for the whole build. Agree on the numbers and the plan. Good looks like one page. It has clear goals for revenue and clients. It has the key numbers: cost per lead, cost per session, cost per client, and the value of a client. The plan names one master num',
        'version': '1.0406bb8e',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': "List the client's current numbers."}, {'name': 'step-02', 'kind': 'task', 'title': 'Set a revenue goal for the year.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Set a client goal for the year.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Work out the value of one client over one year.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Work out the cost per lead, per session, and per client.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the plan on one page.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Set a date to review the plan every 90 days.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Name the one lane to fix first.'}],
        'slug': 'plan',
        'source': 'docs/ops/playbooks/plan.md',
        'roles': [['Delivery lead', 'runs the session and owns the plan.'], ['Coach', 'helps the client set real goals.'], ['Client', 'gives the real numbers.']],
    },
    {
        'definition_id': 'red-playbook-retargeting',
        'kind': 'playbook',
        'title': 'Retargeting playbook',
        'summary': 'This playbook brings back the people who got stuck in the funnel. Show the right ad to the right group. Bring back people who visited but did not act. Follow the steps in order. One audience per funnel step. Use this playbook at Station 7, after traffic is live. Use it on the run line for every funn',
        'version': '1.99df0fcd',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Add tracking and goals to every funnel step.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Split audiences by where each person stopped.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Pick the right group for each ad.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Exclude people who already bought.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write one focused ad for each group.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Use the 5P types for the ad copy.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Show the ad to small groups at low cost.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Measure the result and repeat.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the plan.'}],
        'slug': 'retargeting',
        'source': 'docs/ops/playbooks/retargeting.md',
        'roles': [['Delivery lead', 'owns the plan and the budget.'], ['Ads specialist', 'builds the audiences and the ads.'], ['Coach', 'checks the tracking and the goals.'], ['Client', 'approves the plan.']],
    },
    {
        'definition_id': 'red-playbook-strategy-session',
        'kind': 'playbook',
        'title': 'Strategy session playbook',
        'summary': "This playbook turns a paid roadmap session into a client, with no pressure. Run a paid session that maps the lead's next 90 days. Good looks like a clear plan the lead believes in. The fee filters out people who are not ready, and it earns revenue before the program. Use this playbook for premium of",
        'version': '1.8cf9a888',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Set the session price. Usually $1,000. The floor is $500.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Gate the session with a short application.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Before the session, review the lead against the roadmap.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Run the session. Audit each step. Ask for exact numbers.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Build the 90-day plan with the lead.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Ask the three questions.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Invite them to the program. Apply the fee to month one.'}, {'name': 'step-08', 'kind': 'task', 'title': 'If it is a no, end well and keep the plan.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the roadmap.'}],
        'slug': 'strategy-session',
        'source': 'docs/ops/playbooks/strategy-session.md',
        'roles': [['Enrollment specialist', 'runs the session.'], ['Delivery lead', 'owns the offer and the price.'], ['Coach', 'reviews recorded sessions.'], ['Client', 'approves the roadmap.']],
    },
    {
        'definition_id': 'red-playbook-super-group',
        'kind': 'playbook',
        'title': 'Super group playbook',
        'summary': 'This playbook runs a controlled group that warms leads and creates appointments at little extra cost. Run a group where leads learn from you and raise their hand. Good looks like a group with a clear welcome, a simple filter, and steady posts that lead to a call. The group sits between the lead magn',
        'version': '1.602dbd6b',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Set up the group. Write a clear description with one action.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Write the welcome post. Ask one filter question.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Tag the members who raise their hand.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Plan a simple post calendar.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Post two-step posts, lives, case studies, and useful prompts.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Keep every post inside the signature solution.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Reply to people who engage and invite a call.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Reuse each asset in the group and in the other channels.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Nurture the hand-raisers for about 90 days.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Track who is ready and who needs more time.'}],
        'slug': 'super-group',
        'source': 'docs/ops/playbooks/super-group.md',
        'roles': [['Community manager', 'runs the group and the welcome.'], ['Delivery lead', 'owns the plan and the calendar.'], ['Coach', 'checks the offer fit.'], ['Client', 'posts and replies as the expert.']],
    },
    {
        'definition_id': 'red-playbook-traffic',
        'kind': 'playbook',
        'title': 'Traffic playbook',
        'summary': 'This playbook turns on paid ads the right way. Turn on paid ads the right way. Good looks like a live ad campaign and a metrics dashboard. Watch the few numbers that matter. Change one thing at a time. Use this after the funnel. It is Station 5. - Delivery lead: runs the campaign. - Coach: checks th',
        'version': '1.4c6dc65e',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Set up tracking, audiences, and goals.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Work out the value of a lead. Use the funnel math.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Build a simple campaign: one campaign, one ad set, a few ads.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Launch the campaign.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Leave the new campaign alone for about 10 days.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Watch a few key numbers.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Change only one thing at a time.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Fix things up the funnel, one step at a time.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Test at the top of the funnel first.'}, {'name': 'gate-client', 'kind': 'approval', 'title': 'Client approval: approves the budget.'}],
        'slug': 'traffic',
        'source': 'docs/ops/playbooks/traffic.md',
        'roles': [['Delivery lead', 'runs the campaign.'], ['Coach', 'checks the numbers.'], ['Client', 'approves the budget.']],
    },
    {
        'definition_id': 'red-playbook-webinar',
        'kind': 'playbook',
        'title': 'Webinar playbook',
        'summary': 'This playbook runs a webinar that teaches and sells at scale. It is the scaled path of enrollment. Run one webinar that teaches real value and makes one clear offer. Good looks like a webinar that follows a fixed shape and a fixed clock. It turns many leads into calls at once. Use this playbook afte',
        'version': '1.19330c7a',
        'decisions': [],
        'steps': [{'name': 'step-01', 'kind': 'task', 'title': 'Plan the webinar. Pick the title, the offer, and the price.'}, {'name': 'step-02', 'kind': 'task', 'title': 'Build the slides from the Content Crusher.'}, {'name': 'step-03', 'kind': 'task', 'title': 'Write the frame: promise, who it is for, and who it is not for.'}, {'name': 'step-04', 'kind': 'task', 'title': 'Write three teach blocks. One per phase of the signature solution.'}, {'name': 'step-05', 'kind': 'task', 'title': 'Write the shift: two options and a request to show the program.'}, {'name': 'step-06', 'kind': 'task', 'title': 'Write the sell: a tour, a value stack, the price, and a guarantee.'}, {'name': 'step-07', 'kind': 'task', 'title': 'Write the show: welcome new clients and answer doubts as questions.'}, {'name': 'step-08', 'kind': 'task', 'title': 'Build the pages: sign up, train, webinar, replay, and order.'}, {'name': 'step-09', 'kind': 'task', 'title': 'Send the email sequence. Use the 5P types.'}, {'name': 'step-10', 'kind': 'task', 'title': 'Run the webinar live.'}, {'name': 'step-11', 'kind': 'task', 'title': 'Send the replay to everyone, including people who missed it.'}, {'name': 'step-12', 'kind': 'task', 'title': 'Run the closing sequence for 3 to 5 days.'}, {'name': 'step-13', 'kind': 'task', 'title': 'Retarget each group by where they stopped.'}, {'name': 'step-14', 'kind': 'task', 'title': 'Automate only after ten live runs at 10% or better.'}],
        'slug': 'webinar',
        'source': 'docs/ops/playbooks/webinar.md',
        'roles': [['Delivery lead', 'owns the run of show.'], ['Coach', 'checks the teach and the offer.'], ['Producer', 'builds the slides and the pages.'], ['Client', 'presents the webinar.']],
    },
)
