"""The canon SOPs and playbooks as durable RED workflow definitions (K14;
SPEC.md sections 7 and 14).

``ops_documents_gen`` is generated by ``redops.workflows.sop_import`` from the
pinned canon (docs/ops/sops and docs/ops/playbooks); this module builds the
durable ``WorkflowDefinition`` value objects from that metadata so the definitions
are importable without the canon files present. The derived APPROVAL steps are
the human gates the K12 binding advances with RED approvals. It approves nothing,
spends nothing and deploys nothing.
"""

from __future__ import annotations

from redops.workflows.domain.value_objects import (
    WorkflowDefinition,
    WorkflowStep,
    WorkflowStepKind,
)
from redops.workflows.ops_documents_gen import OPS_DOCUMENT_META


def ops_workflow_definitions() -> dict[str, WorkflowDefinition]:
    """Every imported SOP/playbook definition, keyed by definition id."""

    definitions: dict[str, WorkflowDefinition] = {}
    for meta in OPS_DOCUMENT_META:
        steps = tuple(
            WorkflowStep(name=step["name"], kind=WorkflowStepKind(step["kind"]))
            for step in meta["steps"]
        )
        definitions[meta["definition_id"]] = WorkflowDefinition(
            definition_id=meta["definition_id"],
            version=meta["version"],
            steps=steps,
        )
    return definitions
